# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b38ebdd7b199835c2c0522d7ba68c389c4a67f63c2f1e7cc0f7040cf48158d88f41f2d3e46addc3502a4d68e58b4dbb86975b7fb623880a421a528cf532572b3

test:
  secret_key_base: 42d08b561f374e7933c1d7a517a12f94961843a985012f197a52a331bad12e0007884cfbd8fedcc6dff7e938760a714d8c088566cf6f4a4b6ab3b4eb8e4d274f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
